export enum ActionTypes {
  AUTHLOGIN = "[AUTH] LOGIN",
  AUTHLOGOUT = "[AUTH] LOGOUT",
  AUTHLOADING = "[AUTH] LOADING",
  AUTHRESET = "[AUTH] RESET",

  UIMODALOPEN = "[UI] MODALOPEN",
  UIMODALCLOSE = "[UI] MODALCLOSE",

  EVENTSELECTED = "[EVENT] SELECTED",
  EVENTADD = "[EVENT] ADD",
  EVENTEDIT = "[EVENT] EDIT",
  EVENTDELETE = "[EVENT] DELETE",
  EVENTLOADING = "[EVENT] LOADING",
  EVENTLIST = "[EVENT] LIST",
}
