export enum ActionTypes {
  AUTHLOGIN = "[AUTH] LOGIN",
  AUTHLOGOUT = "[AUTH] LOGOUT",
  AUTHLOADING = "[AUTH] LOADING",
  AUTHRESET = "[AUTH] RESET",

  UIMODALOPEN = "[UI] MODALOPEN",
  UIMODALCLOSE = "[UI] MODALCLOSE",

  EVENTSELECTED = "[EVENT] SELECTED",
}
