export enum ActionTypes {
  AUTHLOGIN = "AUTHLOGIN",
  AUTHLOGOUT = "AUTHLOGOUT",
  AUTHRESET = "AUTHRESET",

  UIMODALOPEN = "[UI] MODALOPEN",
  UIMODALCLOSE = "[UI] MODALCLOSE",

  EVENTSELECTED = "[EVENT] SELECTED",
}
